# Generated by Django 2.0.5 on 2018-09-22 13:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studentprojms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='projreviewers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projid', models.IntegerField(default=0)),
                ('reviewerId', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='projectId',
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 22, 13, 54, 21, tzinfo=utc)),
        ),
    ]
