# Generated by Django 2.0.5 on 2018-09-22 14:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studentprojms', '0002_auto_20180922_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='fid',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='pwd',
        ),
        migrations.AddField(
            model_name='faculty',
            name='n',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 22, 14, 3, 22, tzinfo=utc)),
        ),
    ]
