# Generated by Django 2.0.5 on 2018-09-22 15:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studentprojms', '0003_auto_20180922_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 22, 15, 34, 10, tzinfo=utc)),
        ),
    ]
