# Generated by Django 2.0.5 on 2018-09-27 13:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studentprojms', '0004_auto_20180922_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='contact',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='email',
            field=models.EmailField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 13, 45, 2, tzinfo=utc)),
        ),
    ]
