# Generated by Django 2.0.5 on 2018-09-27 15:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studentprojms', '0006_auto_20180927_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 15, 15, 8, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
