# Generated by Django 2.0.5 on 2018-09-27 18:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studentprojms', '0007_auto_20180927_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='contact',
            new_name='contact1',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='studname',
            new_name='studname1',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='stuid',
            new_name='stuid1',
        ),
        migrations.AddField(
            model_name='project',
            name='contact2',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='contact3',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='email2',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='email3',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='studname2',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='studname3',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='stuid2',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='stuid3',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 18, 15, 27, tzinfo=utc)),
        ),
    ]
