# Generated by Django 2.0.5 on 2018-09-27 18:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studentprojms', '0008_auto_20180927_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contact2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 18, 26, 19, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='email2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='email3',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='studname3',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='stuid2',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='stuid3',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
