# Generated by Django 2.0.5 on 2018-09-28 03:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studentprojms', '0010_auto_20180928_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 3, 56, 51, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='studmarks',
            name='stuid',
            field=models.CharField(max_length=20),
        ),
    ]
