# Generated by Django 2.0.5 on 2018-09-28 08:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('studentprojms', '0011_auto_20180928_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='report',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 8, 15, 50, tzinfo=utc)),
        ),
    ]
